language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'easymock-resource' ]; then cd .. && eval "mv $currentfolder easymock-resource" && cs easymock-resource; fi
